SYMBOL = "XAUUSD"

M15_BARS = 50
H1_BARS = 100

M15_TIMEFRAME_NAME = "M15"
H1_TIMEFRAME_NAME = "H1"

EMA_FAST = 20
EMA_SLOW = 50

RSI_PERIOD = 14
ATR_PERIOD = 14

STATUS_NO_TRADE = "NO TRADE"
STATUS_WATCH = "WATCH"
STATUS_PULLBACK_BUY = "PULLBACK BUY"
STATUS_SELL_WATCH = "SELL WATCH"
STATUS_BREAKOUT_WATCH = "BREAKOUT WATCH"
STATUS_BREAKDOWN_WATCH = "BREAKDOWN WATCH"
SIGNAL_WEAK = "WEAK"
SIGNAL_MEDIUM = "MEDIUM"
SIGNAL_STRONG = "STRONG"
FINAL_SIGNAL_BUY = "BUY"
FINAL_SIGNAL_SELL = "SELL"
FINAL_SIGNAL_WAIT = "WAIT"


